# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 10:51
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0006_cohort_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='oauth_secret',
            field=models.CharField(help_text='Required. 255 characters or fewer. Letters, digits, spaces and punctuation only.', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(b'^[\\w\\s,;|.!@#$%^&*()?+_-]+$', 'Enter a valid oauth secret.', b'invalid')], verbose_name='oauth secret'),
        ),
    ]
